---
- name: Create /etc/fluent-bit/fluent-bit.conf
  ansible.builtin.copy:
    src: fluent-bit.conf
    dest: /etc/fluent-bit/fluent-bit.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart fluent-bit