---
- name: Create /etc/nginx/nginx.conf
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: "0644"
  notify: Reload nginx

- name: Create /etc/nginx/sites-enabled/myrs.conf
  ansible.builtin.template:
    src: myrs.conf.j2
    dest: /etc/nginx/sites-enabled/myrs.conf
    owner: root
    group: root
    mode: "0644"
  notify: Reload nginx
  when: is_production|default(false)
